# Generated by Django 5.1.2 on 2026-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('court_type', models.CharField(choices=[('FOOTBALL', 'Futbol'), ('BASKETBALL', 'Baloncesto'), ('TENNIS', 'Tenis'), ('PADEL', 'Padel'), ('VOLLEYBALL', 'Voleibol'), ('OTHER', 'Otra')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courts/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('MAINTENANCE', 'En mantenimiento'), ('OCCUPIED', 'Ocupada')], default='AVAILABLE', max_length=20)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('available_weekdays', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courts',
                'ordering': ['name'],
            },
        ),
    ]
